-- Welcome and quick_menu flex carousel payloads (shared LINE Flex shape for Web + LINE).

update public.bot_messages
set
  type = 'flex',
  body = 'PET TAXIへようこそ。まずはこちらからご確認ください。',
  payload = '{"line":{"type":"flex","altText":"PET TAXIへようこそ","contents":{"type":"carousel","contents":[{"type":"bubble","hero":{"type":"image","url":"/images/quick-menu.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"クイックメニュー","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"予約や確認を素早く選べます。","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"開く","data":"quick_menu"}}]}},{"type":"bubble","hero":{"type":"image","url":"/images/how-yo-use.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"使い方","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"チャットで予約相談や確認ができます。","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"詳しく見る","data":"how_to_use"}}]}},{"type":"bubble","hero":{"type":"image","url":"/images/FAQ.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"FAQ","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"料金や予約方法などを確認できます。","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"見る","data":"faq"}}]}}]}}}'::jsonb
where key = 'welcome'
  and locale = 'ja';

update public.bot_messages
set
  type = 'flex',
  body = 'Welcome to PET TAXI. Start here.',
  payload = '{"line":{"type":"flex","altText":"Welcome to PET TAXI","contents":{"type":"carousel","contents":[{"type":"bubble","hero":{"type":"image","url":"/images/quick-menu.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"Quick Menu","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"Choose booking and support options quickly.","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"Open","data":"quick_menu"}}]}},{"type":"bubble","hero":{"type":"image","url":"/images/how-yo-use.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"How to use","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"Book, ask, and confirm through chat.","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"Learn more","data":"how_to_use"}}]}},{"type":"bubble","hero":{"type":"image","url":"/images/FAQ.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"FAQ","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"Check pricing, areas, and booking steps.","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"View","data":"faq"}}]}}]}}}'::jsonb
where key = 'welcome'
  and locale = 'en';

update public.bot_messages
set
  type = 'flex',
  body = 'Bienvenido a PET TAXI. Empieza aqui.',
  payload = '{"line":{"type":"flex","altText":"Bienvenido a PET TAXI","contents":{"type":"carousel","contents":[{"type":"bubble","hero":{"type":"image","url":"/images/quick-menu.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"Menu rapido","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"Elige reservas y soporte rapidamente.","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"Abrir","data":"quick_menu"}}]}},{"type":"bubble","hero":{"type":"image","url":"/images/how-yo-use.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"Como usar","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"Reserva, consulta y confirma por chat.","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"Ver mas","data":"how_to_use"}}]}},{"type":"bubble","hero":{"type":"image","url":"/images/FAQ.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"FAQ","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"Consulta precios, zonas y reservas.","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"Ver","data":"faq"}}]}}]}}}'::jsonb
where key = 'welcome'
  and locale = 'es';

update public.bot_messages
set
  type = 'flex',
  body = 'クイックメニューからご希望の内容を選んでください。',
  payload = '{"line":{"type":"flex","altText":"クイックメニュー","contents":{"type":"carousel","contents":[{"type":"bubble","hero":{"type":"image","url":"/images/how-yo-use.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"使い方","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"予約、相談、確認をチャットで進められます。","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"見る","data":"how_to_use"}}]}},{"type":"bubble","hero":{"type":"image","url":"/images/FAQ.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"FAQ","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"よくある質問を確認できます。","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"見る","data":"faq"}}]}},{"type":"bubble","hero":{"type":"image","url":"/images/bot-mode.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"Botモード","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"自動案内で素早く確認します。","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"切り替える","data":"bot_mode"}}]}},{"type":"bubble","hero":{"type":"image","url":"/images/concierge-mode.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"Concierge","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"スタッフに相談します。","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"相談する","data":"concierge_mode"}}]}}]}}}'::jsonb
where key = 'quick_menu'
  and locale = 'ja';

update public.bot_messages
set
  type = 'flex',
  body = 'Choose an option from the quick menu.',
  payload = '{"line":{"type":"flex","altText":"Quick Menu","contents":{"type":"carousel","contents":[{"type":"bubble","hero":{"type":"image","url":"/images/how-yo-use.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"How to use","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"Book, ask, and confirm through chat.","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"View","data":"how_to_use"}}]}},{"type":"bubble","hero":{"type":"image","url":"/images/FAQ.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"FAQ","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"Check common questions.","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"View","data":"faq"}}]}},{"type":"bubble","hero":{"type":"image","url":"/images/bot-mode.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"Bot mode","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"Use automated guidance for quick answers.","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"Switch","data":"bot_mode"}}]}},{"type":"bubble","hero":{"type":"image","url":"/images/concierge-mode.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"Concierge","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"Talk with our staff.","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"Contact","data":"concierge_mode"}}]}}]}}}'::jsonb
where key = 'quick_menu'
  and locale = 'en';

update public.bot_messages
set
  type = 'flex',
  body = 'Elige una opcion del menu rapido.',
  payload = '{"line":{"type":"flex","altText":"Menu rapido","contents":{"type":"carousel","contents":[{"type":"bubble","hero":{"type":"image","url":"/images/how-yo-use.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"Como usar","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"Reserva, consulta y confirma por chat.","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"Ver","data":"how_to_use"}}]}},{"type":"bubble","hero":{"type":"image","url":"/images/FAQ.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"FAQ","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"Consulta preguntas frecuentes.","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"Ver","data":"faq"}}]}},{"type":"bubble","hero":{"type":"image","url":"/images/bot-mode.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"Modo Bot","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"Usa guia automatica para respuestas rapidas.","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"Cambiar","data":"bot_mode"}}]}},{"type":"bubble","hero":{"type":"image","url":"/images/concierge-mode.jpg","size":"full","aspectRatio":"20:13","aspectMode":"cover"},"body":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"16px","contents":[{"type":"text","text":"Conserje","weight":"bold","size":"md","color":"#3d2a19"},{"type":"text","text":"Habla con nuestro equipo.","wrap":true,"size":"sm","color":"#8c7358"}]},"footer":{"type":"box","layout":"vertical","spacing":"sm","paddingAll":"12px","contents":[{"type":"button","style":"primary","color":"#8f5d28","height":"sm","action":{"type":"postback","label":"Contactar","data":"concierge_mode"}}]}}]}}}'::jsonb
where key = 'quick_menu'
  and locale = 'es';
