import { group_city_options, type AddressOptions } from "@/src/address/rules"

const prefecture_rows = [
  { code: "01", label: "北海道" },
  { code: "02", label: "青森県" },
  { code: "03", label: "岩手県" },
  { code: "04", label: "宮城県" },
  { code: "05", label: "秋田県" },
  { code: "06", label: "山形県" },
  { code: "07", label: "福島県" },
  { code: "08", label: "茨城県" },
  { code: "09", label: "栃木県" },
  { code: "10", label: "群馬県" },
  { code: "11", label: "埼玉県" },
  { code: "12", label: "千葉県" },
  { code: "13", label: "東京都" },
  { code: "14", label: "神奈川県" },
  { code: "15", label: "新潟県" },
  { code: "16", label: "富山県" },
  { code: "17", label: "石川県" },
  { code: "18", label: "福井県" },
  { code: "19", label: "山梨県" },
  { code: "20", label: "長野県" },
  { code: "21", label: "岐阜県" },
  { code: "22", label: "静岡県" },
  { code: "23", label: "愛知県" },
  { code: "24", label: "三重県" },
  { code: "25", label: "滋賀県" },
  { code: "26", label: "京都府" },
  { code: "27", label: "大阪府" },
  { code: "28", label: "兵庫県" },
  { code: "29", label: "奈良県" },
  { code: "30", label: "和歌山県" },
  { code: "31", label: "鳥取県" },
  { code: "32", label: "島根県" },
  { code: "33", label: "岡山県" },
  { code: "34", label: "広島県" },
  { code: "35", label: "山口県" },
  { code: "36", label: "徳島県" },
  { code: "37", label: "香川県" },
  { code: "38", label: "愛媛県" },
  { code: "39", label: "高知県" },
  { code: "40", label: "福岡県" },
  { code: "41", label: "佐賀県" },
  { code: "42", label: "長崎県" },
  { code: "43", label: "熊本県" },
  { code: "44", label: "大分県" },
  { code: "45", label: "宮崎県" },
  { code: "46", label: "鹿児島県" },
  { code: "47", label: "沖縄県" },
] as const

const city_rows = [
  { code: "01100", prefecture_code: "01", label: "札幌市" },
  { code: "02201", prefecture_code: "02", label: "青森市" },
  { code: "03201", prefecture_code: "03", label: "盛岡市" },
  { code: "04100", prefecture_code: "04", label: "仙台市" },
  { code: "05201", prefecture_code: "05", label: "秋田市" },
  { code: "06201", prefecture_code: "06", label: "山形市" },
  { code: "07201", prefecture_code: "07", label: "福島市" },
  { code: "08201", prefecture_code: "08", label: "水戸市" },
  { code: "09201", prefecture_code: "09", label: "宇都宮市" },
  { code: "10201", prefecture_code: "10", label: "前橋市" },
  { code: "11100", prefecture_code: "11", label: "さいたま市" },
  { code: "12100", prefecture_code: "12", label: "千葉市" },
  { code: "13101", prefecture_code: "13", label: "千代田区" },
  { code: "13102", prefecture_code: "13", label: "中央区" },
  { code: "13103", prefecture_code: "13", label: "港区" },
  { code: "13104", prefecture_code: "13", label: "新宿区" },
  { code: "13113", prefecture_code: "13", label: "渋谷区" },
  { code: "14100", prefecture_code: "14", label: "横浜市" },
  { code: "15100", prefecture_code: "15", label: "新潟市" },
  { code: "16201", prefecture_code: "16", label: "富山市" },
  { code: "17201", prefecture_code: "17", label: "金沢市" },
  { code: "18201", prefecture_code: "18", label: "福井市" },
  { code: "19201", prefecture_code: "19", label: "甲府市" },
  { code: "20201", prefecture_code: "20", label: "長野市" },
  { code: "21201", prefecture_code: "21", label: "岐阜市" },
  { code: "22100", prefecture_code: "22", label: "静岡市" },
  { code: "23100", prefecture_code: "23", label: "名古屋市" },
  { code: "24201", prefecture_code: "24", label: "津市" },
  { code: "25201", prefecture_code: "25", label: "大津市" },
  { code: "26100", prefecture_code: "26", label: "京都市" },
  { code: "27100", prefecture_code: "27", label: "大阪市" },
  { code: "28100", prefecture_code: "28", label: "神戸市" },
  { code: "29201", prefecture_code: "29", label: "奈良市" },
  { code: "30201", prefecture_code: "30", label: "和歌山市" },
  { code: "31201", prefecture_code: "31", label: "鳥取市" },
  { code: "32201", prefecture_code: "32", label: "松江市" },
  { code: "33100", prefecture_code: "33", label: "岡山市" },
  { code: "34100", prefecture_code: "34", label: "広島市" },
  { code: "35203", prefecture_code: "35", label: "山口市" },
  { code: "36201", prefecture_code: "36", label: "徳島市" },
  { code: "37201", prefecture_code: "37", label: "高松市" },
  { code: "38201", prefecture_code: "38", label: "松山市" },
  { code: "39201", prefecture_code: "39", label: "高知市" },
  { code: "40130", prefecture_code: "40", label: "福岡市" },
  { code: "41201", prefecture_code: "41", label: "佐賀市" },
  { code: "42201", prefecture_code: "42", label: "長崎市" },
  { code: "43100", prefecture_code: "43", label: "熊本市" },
  { code: "44201", prefecture_code: "44", label: "大分市" },
  { code: "45201", prefecture_code: "45", label: "宮崎市" },
  { code: "46201", prefecture_code: "46", label: "鹿児島市" },
  { code: "47201", prefecture_code: "47", label: "那覇市" },
] as const

export const ADDRESS_OPTIONS_DATA: AddressOptions = {
  prefectures: [...prefecture_rows],
  cities_by_prefecture: group_city_options([...city_rows]),
}
